sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
before_script: ## 根据你所用的主题和自定义的不同，这里会有所不同
  - cd blog # 在 CI 环境内安装 Hexo
  - npm install -g hexo-cli # 在 CI 环境内安装 Hexo
  - cd themes
  - git clone https://github.com/SukkaW/hexo-theme-suka.git suka #从 Github 上拉取 Suka 主题
  - cd suka
  - npm install --production # 安装 Suka 主题的依赖
  - cp -i _config.example.yml _config.yml
  - cd ../../ # 返回站点根目录
  - cat themes/suka/site_config.yml >> _config.yml
  - npm install # 在根目录安装站点需要的依赖
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: master
  local-dir: public
